<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

use AppBundle\Entity\User;

/**
 * BlockSettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlockSettingsRepository extends EntityRepository
{
    public function getStatsForUser(User $user)
    {
        return $this->createQueryBuilder('b')
            ->select('b')
            ->where('b.user = :user')
            ->setParameter('user', $user)
            ->getQuery()->getArrayResult();
    }
}
