<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GroupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupsRepository extends EntityRepository
{
    public function byUserIndexedByGroupIds(User $user)
    {
        $q = $this->getEntityManager()
            ->createQuery("SELECT g FROM AppBundle:Groups g INDEX BY g.user WHERE g.user = " . $user);

        return $q->getArrayResult();
    }
}
