<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlacesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlacesRepository extends EntityRepository
{
    public function countForUser(User $user)
    {
        $q = $this->createQueryBuilder('t')
            ->select('COUNT(t)')
            ->where('t.user = :user')
            ->setParameter('user', $user);

        return $q->getQuery()->getSingleScalarResult();
    }
}
