<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RubricsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RubricsRepository extends EntityRepository
{
}
