<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatRepository extends EntityRepository
{
    public function getStatForBlocks($blocks = array())
    {
        $q = $this->getEntityManager()
            ->createQuery('SELECT s FROM AppBundle:Stat s WHERE s.blockSettings IN(' . implode(',', $blocks) . ')');

        return $q->getArrayResult();
    }

}
