<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TeasersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeasersRepository extends EntityRepository
{

    public function getRandomWithLimit(Groups $group, Rubrics $rubric, $limit = 1) {

        $q = $this->createQueryBuilder('t')
            ->select('t')
            ->addSelect('RAND() as HIDDEN rand')
            ->where('t.groups = :group')
            ->andWhere('t.rubrics = :rubric')

            ->setParameter('group', $group)
            ->setParameter('rubric', $rubric)

            ->addOrderBy('rand')
            ->setMaxResults($limit)
        ;

        return $q->getQuery()->getResult();
    }

    public function idsByGroups($groupIds = array())
    {
        $q = $this->createQueryBuilder('t')
            ->select('t')
            ->andWhere('t.groups IN (:ids)')
            ->setParameter('ids', $groupIds);

        return $q->getQuery()->getResult();
    }

}
